/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reviewer;

/**
 *
 * @author CL1-PC16
 */
public class receiptgrades extends javax.swing.JFrame {

    /**
     * Creates new form receiptgrades
     */
    public receiptgrades(String name, String section, float average) {
        initComponents();
        lblname.setText("Name: " + name);
        lblsection.setText("Section: " + section);
        lblaverage.setText("Average: " + average);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblsection = new javax.swing.JLabel();
        lblaverage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("GRADES RECEIPTS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        lblname.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblname.setText("Name:");
        getContentPane().add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        lblsection.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblsection.setText("Section:");
        getContentPane().add(lblsection, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        lblaverage.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblaverage.setText("Total Average:");
        getContentPane().add(lblaverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receiptgrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receiptgrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receiptgrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receiptgrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblaverage;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblsection;
    // End of variables declaration//GEN-END:variables
}
