/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reviewer;

import javax.swing.JOptionPane;

/**
 *
 * @author CL1-PC16
 */
public class RPSwithHealthBar extends javax.swing.JFrame {

        int health1 = 5;
        int health2 = 5;
    public RPSwithHealthBar() {
        initComponents();
        txthealth1.setEditable(false);
        txthealth2.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtplayer1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtplayer2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txthealth2 = new javax.swing.JTextField();
        txthealth1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel3.setText("ROCK, PAPER, SCISSORS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 270, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("[2] Paper");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("[1] Rock");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("[3] Scissors");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));
        getContentPane().add(txtplayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 150, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Player 1 :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Player 2 :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        getContentPane().add(txtplayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 150, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("VS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 150, -1));

        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 80, 30));
        getContentPane().add(txthealth2, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 190, 80, 30));
        getContentPane().add(txthealth1, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 140, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int player1 = Integer.parseInt(txtplayer1.getText());
        int player2 = Integer.parseInt(txtplayer2.getText());
        txtplayer1.setText("");
        txtplayer2.setText("");
        
        if (player1 == 1 && player2 == 2 ||
            player1 == 2 && player2 == 2 ||
            player1 == 3 && player2 == 3){
            
            JOptionPane.showMessageDialog(null, "Draw", "Rock, Paper and Scissors", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(player1 == 1 && player2 == 2 ||
                player1 == 2 && player2 == 3 ||
                player1 == 3 && player2 == 1){
                health1--;
            
            JOptionPane.showMessageDialog(null, "Player 2 Wins", "Rock, Paper and Scissors", JOptionPane.INFORMATION_MESSAGE);
        } 
        else if (player1 == 1 && player2 == 3 ||
                 player1 == 2 && player2 == 1 ||
                 player1 == 3 && player2 == 2) {
                 health2--;
            
            JOptionPane.showMessageDialog(null, "Player 1 Wins", "Rock, Paper and Scissors", JOptionPane.INFORMATION_MESSAGE);
             
        } 
        else {
            JOptionPane.showMessageDialog(null, "Incorrect Input!", "Rock, Paper and Scissors", JOptionPane.INFORMATION_MESSAGE);
        }
        
        txthealth1.setText(String.valueOf(health1));
        txthealth2.setText(String.valueOf(health2));
        
        
        if (health1 == 0){
            JOptionPane.showMessageDialog(null, "Player 2 wins the game!", "Game over!", JOptionPane.INFORMATION_MESSAGE);
            health1 = 5;
            health2 = 5;
        }
        else if (health2 == 0){
            health1 = 5;
            health2 = 5;
        }
        txthealth1.setText(String.valueOf(health1));
        txthealth2.setText(String.valueOf(health2));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPSwithHealthBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPSwithHealthBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPSwithHealthBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPSwithHealthBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPSwithHealthBar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txthealth1;
    private javax.swing.JTextField txthealth2;
    private javax.swing.JTextField txtplayer1;
    private javax.swing.JTextField txtplayer2;
    // End of variables declaration//GEN-END:variables
}
