/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reviewer;

import javax.swing.JOptionPane;

/**
 *
 * @author CL1-PC16
 */
public class TryTicTacToe extends javax.swing.JFrame {

    /**
     * Creates new form TryTicTacToe
     */
    public TryTicTacToe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtleftside1 = new javax.swing.JTextField();
        txtleftside3 = new javax.swing.JTextField();
        txtrightside3 = new javax.swing.JTextField();
        txtcenter3 = new javax.swing.JTextField();
        txtcenter1 = new javax.swing.JTextField();
        txtrightside1 = new javax.swing.JTextField();
        txtrightside2 = new javax.swing.JTextField();
        txtleftside2 = new javax.swing.JTextField();
        txtcenter2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtscore2 = new javax.swing.JTextField();
        txtscore1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtleftside1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtleftside1.setText("5");
        getContentPane().add(txtleftside1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 60, 50));

        txtleftside3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtleftside3.setText("5");
        getContentPane().add(txtleftside3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 60, 50));

        txtrightside3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtrightside3.setText("5");
        getContentPane().add(txtrightside3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 60, 50));

        txtcenter3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtcenter3.setText("5");
        getContentPane().add(txtcenter3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 60, 50));

        txtcenter1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtcenter1.setText("5");
        getContentPane().add(txtcenter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 60, 50));

        txtrightside1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtrightside1.setText("5");
        getContentPane().add(txtrightside1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 60, 50));

        txtrightside2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtrightside2.setText("5");
        getContentPane().add(txtrightside2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 60, 50));

        txtleftside2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtleftside2.setText("5");
        txtleftside2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtleftside2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtleftside2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 60, 50));

        txtcenter2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtcenter2.setText("5");
        getContentPane().add(txtcenter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 60, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("TIC TAC TOE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        txtscore2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        txtscore2.setText("0");
        txtscore2.setEnabled(false);
        getContentPane().add(txtscore2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, 50));

        txtscore1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        txtscore1.setText("0");
        txtscore1.setEnabled(false);
        txtscore1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtscore1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtscore1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        jLabel2.setText("PLAYER 2 SCORE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        jLabel3.setText("PLAYER 1 SCORE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setText("CHECK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("[0] Player 2");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 275, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("[1] Player 1");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtleftside2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtleftside2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtleftside2ActionPerformed

    private void txtscore1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtscore1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtscore1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int left1 = Integer.parseInt(txtleftside1.getText());
        int left2 = Integer.parseInt(txtleftside2.getText());
        int left3 = Integer.parseInt(txtleftside3.getText());
        
        int center1 = Integer.parseInt(txtcenter1.getText());
        int center2 = Integer.parseInt(txtcenter2.getText());
        int center3 = Integer.parseInt(txtcenter3.getText());
        
        int right1 = Integer.parseInt(txtrightside1.getText());
        int right2 = Integer.parseInt(txtrightside2.getText());
        int right3 = Integer.parseInt(txtrightside3.getText());
        
        if ((left1 == 1 && center1 == 1 && right1 == 1)||
            (left2 == 1 && center2 == 1 && right2 == 1)||
            (left3 == 1 && center3 == 1 && right3 == 1)||
            (left1 == 1 && left2 == 1 && left3 == 1) ||
            (center1 == 1 && center2 == 1 && center3 == 1) ||
            (right1 == 1 && right2 == 1 && right3 == 1) ||
            (left1 == 1 && center2 == 1 && right3 == 1) ||
            (right1 == 1 && center2 == 1 && left3 == 1)){
            
            int score = Integer.parseInt(txtscore1.getText());
            
            score++;
            
            txtscore1.setText(String.valueOf(score));
            
            JOptionPane.showMessageDialog(null, "PLAYER 1 WINS", "TIC TAC TOE", JOptionPane.INFORMATION_MESSAGE);
            if (score >= 5){
               JOptionPane.showMessageDialog(null, "PLAYER 1 WINS", "TIC TAC TOE", JOptionPane.INFORMATION_MESSAGE); 
               disableBoard();
            }
        }
       
        else if ((left1 == 0 && center1 == 0 && right1 == 0) ||
                (left2 == 0 && center2 == 0 && right2 == 0) ||
                (left3 == 0 && center3 == 0 && right3 == 0) ||
                (left1 == 0 && left2 == 0 && left3 == 0) ||
                (center1 == 0 && center2 == 0 && center3 == 0) ||
                (right1 == 0 && right2 == 0 && right3 == 0) ||
                (left1 == 0 && center2 == 0 && right3 == 0) ||
                (right1 == 0 && center2 == 0 && left3 == 0)){
            
                int score = Integer.parseInt(txtscore2.getText());
            
                score++;
            
                txtscore2.setText(String.valueOf(score));
            
                JOptionPane.showMessageDialog(null, "PLAYER 2 WINS", "TIC TAC TOE", JOptionPane.INFORMATION_MESSAGE);
            if (score >= 5){
                JOptionPane.showMessageDialog(null, "PLAYER 2 WINS", "TIC TAC TOE", JOptionPane.showMessageDialog.INFORMATION_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "TIC TAC TOE", "No winners yet!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void disableBoard() {
        txtleftside1.setEditable(false);
        txtleftside2.setEditable(false);
        txtleftside3.setEditable(false);
        txtcenter1.setEditable(false);
        txtcenter2.setEditable(false);
        txtcenter3.setEditable(false);
        txtrightside1.setEditable(false);
        txtrightside2.setEditable(false);
        txtrightside3.setEditable(false);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtleftside1.setText("");
        txtleftside2.setText("");
        txtleftside3.setText("");
        txtcenter1.setText("");
        txtcenter2.setText("");
        txtcenter3.setText("");
        txtrightside1.setText("");
        txtrightside2.setText("");
        txtrightside3.setText("");
        
        txtleftside1.setEditable(true);
        txtleftside2.setEditable(true);
        txtleftside3.setEditable(true);
        txtcenter1.setEditable(true);
        txtcenter2.setEditable(true);
        txtcenter3.setEditable(true);
        txtrightside1.setEditable(true);
        txtrightside2.setEditable(true);
        txtrightside3.setEditable(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TryTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TryTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TryTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TryTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TryTicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtcenter1;
    private javax.swing.JTextField txtcenter2;
    private javax.swing.JTextField txtcenter3;
    private javax.swing.JTextField txtleftside1;
    private javax.swing.JTextField txtleftside2;
    private javax.swing.JTextField txtleftside3;
    private javax.swing.JTextField txtrightside1;
    private javax.swing.JTextField txtrightside2;
    private javax.swing.JTextField txtrightside3;
    private javax.swing.JTextField txtscore1;
    private javax.swing.JTextField txtscore2;
    // End of variables declaration//GEN-END:variables
}
